### ISSUE TITLE
Add option `emitFile` to avoid emitting files on server side

### ISSUE THREAD

**Issue by cusspvz** [metalabdesign/sharp-loader#17]
Add a query option `emitFile`, as present on `file-loader`, that disables the file emitting for building up for the server-side on a Universal/Isomorphic environment.

related with webpack-contrib/file-loader#74

**Comment by izaakschroeder** [comment]
Good point! I think this has been in the works for a bit now but I've just never gotten around to it. I'll see what I can do in the next week or so here. 😄
