### ISSUE TITLE
Error when trying to config chain it to webpack

### ISSUE THREAD

**Issue by gvstavnev** [metalabdesign/sharp-loader#30]
I'm currently working on a vue project and tried to translate your example config to chainWebpack syntax and include it in my vue.config.js.
This is what i came up with:

```js
module.exports = {
  chainWebpack: config => {
    config.module
        .rule('resize-images')
        .test(/\.(gif|jpe?g|png|tiff)(\?.*)?$/)
        .use('sharp-loader')
            .loader('sharp-loader')
                .query()
                    .name('[name].[hash:8].[ext]')
                    .cacheDirectory(true)
                    .presets()
                        .thumbnail()
                            .format(['webp', 'jpeg'])
                            .width(200)
                            .quality(60)
                .end()
    }
}
```
Getting following error:
```
 ERROR  TypeError: config.module.rule(...).test(...).use(...).loader(...).query is not a function
```

I saw that other loaders in my webpack config used `options:` instead of 
`query:` and i think thats the issue – i tried the following and got no more errors:

```js
module.exports = {
  chainWebpack: config => {
    config.module
        .rule('resize-images')
        .test(/\.(gif|jpe?g|png|tiff)(\?.*)?$/)
        .use('sharp-loader')
            .loader('sharp-loader')
                .options()
                .end()
    }
}
```

I'm currently on  ` webpack@4.26.1`.

Thank you for your work!

**Comment by izaakschroeder** [comment]
Would have to dig into it a bit further since I haven't used the chaining mechanism you're showing here (and in general prefer function composition over anything else: https://medium.com/making-internets/webpack-configuration-done-right-86c325a6927f). I'm _guessing_ what you're looking for should look something like:

```js
// ...
  .options({
    presets: {
      thumbnail: {
        format: ['webp', {id: 'jpeg', quality: 60}],
        width: 200,
      }
    }
  })
  .end()
```

Note that the `format` object syntax is a side effect of the most current `sharp` version's expectation of `format()`: https://sharp.dimens.io/en/stable/api-output/#parameters_7.

**Comment by gvstavnev** [comment]
Thank you very much, seems like it works well. 
I'am bit new to that whole webpack stuff – thank your for your help :-)

**Comment by gvstavnev** [comment]
Can you give me a hint on how to specify the output directory for the resized images? At the moment they get placed at the roots directory.

**Comment by gvstavnev** [comment]
@izaakschroeder 
maybe you can help me. I'am currently stuck – I achieved the right image rendering according to my config… but it returns the wrong path to the `<img>` tag. 

My template:
```html
<img src="../assets/parallaxPage03.png" class="logo">
```

and I get:
```
<img data-v-611b1de2="" src="data:image/png;base64,bW9kdWxlLmV4cG9ydHMgPSBbeyJuYW1lIjogImltZ1x1MDAyRnBhcmFsbGF4UGFnZTAyLjU4N2ViMDkwLnBuZyIsIndpZHRoIjogMTAwLCJmb3JtYXQiOiAicG5nIiwicHJlc2V0IjogInRodW1ibmFpbCIsImhlaWdodCI6IDQxLCJ0eXBlIjogImltYWdlXHUwMDJGcG5nIiwidXJsIjogX193ZWJwYWNrX3B1YmxpY19wYXRoX18gKyAiaW1nXHUwMDJGcGFyYWxsYXhQYWdlMDIuNTg3ZWIwOTAucG5nIn1dOw==" class="logo">
```
